### PR TITLE
Default RAID configuration

### PR DESCRIPTION
**Pull request by xek**

### CODE REVIEW

**Comment by xek** [comment]
@epim I called the field in ``instance_info`` ``"default_raid"`` let me know if this needs to be changed.

**Comment by jimrollenhagen** [comment]
So, the default RAID mode should be stored on `driver_info` or something. `instance_info` is removed after every instance, so doesn't really make sense for a default setting.

Also, I imagine we want to handle default RAID modes in one of two ways:

* when we are deploying, if there is no RAID mode specified, use the default RAID (this patch currently *always* configures the default RAID, even if it won't be used)
* Always set up the default RAID mode during cleaning, so it's ready to go when we want to deploy.

We should pick one and fix this patch to do that thing.

**Comment by xek** [comment]
What do you mean by "creating a RAID that is not being used"? A RAID array is created for each disk specified in the disk_config, so they will all be partitioned, formatted and mounted in the new installed system.

There is a cleaning step when running SystemInstaller().install(), which removes all LVMs, software and hardware RAIDs before configuring new ones.

**Comment by xek** [comment]
Ok, I think I understood what you meant :) The default_raid configuration in this implementation overwrites the hardware RAID configuration from the disk_config, which shouldn't be the case. It should only create the default RAID configuration when there is no raid specified in the config.

Let me know if it is everything you meant to say.

**Comment by jimrollenhagen** [comment]
> The default_raid configuration in this implementation overwrites the hardware RAID configuration from the disk_config, which shouldn't be the case.

I think the RAID config from the disk_config will overwrite the default.

> It should only create the default RAID configuration when there is no raid specified in the config.

But yes, this is what I'm saying. But now that I think more about it, we would need to make sure that *all* disks have a RAID configuration specified in disk_config, not just some. So maybe the easiest route is to write the default raid config during cleaning? Should be an easy clean step to make, and can be out of tree instead of a patch. :D

This also does seem like it would work, we could just do this for now and optimize later. :)

**Comment by jimrollenhagen** [comment]
Merging this, not fully tested (waiting for hardware) but will clean up later as needed.

**Pull request merged**
